language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: qHdUT4ioWdJk8Vsk1QcWRU88miY/VEOHUSaRMYGs66/KwjKJZTXwwEpaU0O10AZvlX+xGwvg2omzrc0MY6YMu6Zol/PiGcI0yDD06LAOIW2J+X2877vw5YvQBZMW2iSL7bF8utOt5SpxtYEIV58tNHZwbFCS0zTDpqj62chKlFHOi+c95fqV33upRUx3vjVCbz0VdGIjsgyg++4Us2qZawfilhfsvNqG1UoJTdZqG5qvEJJ10IxnJqRTylrzzn+h2wP3RODmuWTYOhSQj8maE+jdlTb5bt0vd2Omo/Rd8dsAOWY87qsaL8x2hTcQO3dM9p07QjyhVu62YLfEqMP0TclnHb0L4t9mu5FVkp8aNs7ocL2tqh8B0RBTZSx1m0IVfOe6HSDNsGuMxZai2Zk9dZLxQyWO9Y66ohH3wv34MPtFvrdBBCB60Kcc4DjRNjSirFqU716zF0PzmkKLA55z2Txbqcqp3qBnMUojuDtuSkfquy5+/30q6ssfQV6czy/Sp/4zZMyb2X3Oq2smk/cb593rVQ/KtJIkjNByw+WZk90z6tXMQvxkhftNVjZxmBXZC70igV+zaWNAYwXQMGPkp+dcu5IkeX3GTfry50Z4BKfHmkJzgT3l4d6FpeO0yynzmHH6jSHxXsbnoo32CDWyhYTpdZPq/0LL1afWd13h9rk=
  file:
    - 'unist-util-assert.js'
    - 'unist-util-assert.min.js'
  on:
    tags: true
